const Reservation = require("../Model/ReservationModel");
const Seat = require("../Model/SeatModel");

//CREATE
const createReservation = async (req, res) => {
  try {
    const { 
      studentID, 
      busID, 
      seatNumber, 
      reservationType, 
      startDate, 
      endDate, 
      daysBooked, 
      seasonType 
    } = req.body;

    // Find the seat by busID and seatNumber
    const seat = await Seat.findOne({ busID, seatNumber });
    if (!seat) return res.status(404).json({ error: "Seat not found" });
    
    // Check seat availability
    if (seat.status === "Available") {
      // Seat is available for anyone
    } else if (seat.status === "Pending" && reservationType === "Regular") {
      // Check if this student can renew their previous seat
      const lastReservation = await Reservation.findOne({
        busID,
        seatNumber,
        studentID,
        status: "Completed",
        reservationType: "Regular"
      }).sort({ endDate: -1 });
      
      if (!lastReservation) {
        return res.status(400).json({ 
          error: "This seat is pending renewal by another student" 
        });
      }
      
      // Check if the renewal is within grace period (e.g., 30 days)
      const daysSinceExpiry = Math.floor((new Date() - new Date(lastReservation.endDate)) / (1000 * 60 * 60 * 24));
      if (daysSinceExpiry > 30) {
        return res.status(400).json({ 
          error: "Renewal period has expired. This seat is no longer available for renewal." 
        });
      }
    } else {
      return res.status(400).json({ error: "Seat is not available" });
    }

    // Check if student already has an active reservation (prevent multiple bookings)
    const existingReservation = await Reservation.findOne({
      studentID: studentID,
      status: { $in: ["Booked", "Reserved"] }
    });

    if (existingReservation) {
      return res.status(400).json({ 
        error: `Student ${studentID} already has an active reservation (${existingReservation.reservationID}) for Bus ${existingReservation.busID}, Seat ${existingReservation.seatNumber}. Only one active reservation per student is allowed.`,
        existingReservation: {
          reservationID: existingReservation.reservationID,
          busID: existingReservation.busID,
          seatNumber: existingReservation.seatNumber,
          status: existingReservation.status,
          startDate: existingReservation.startDate,
          endDate: existingReservation.endDate
        }
      });
    }

    // Calculate fee based on reservation type
    let feeAmount = 0;
    let feeBreakdown = {
      registrationFee: 1000, // Updated registration fee
      monthlyFee: 0,
      annualFee: 0,
      dailyFee: 0
    };

    if (reservationType === "Regular") {
      if (seasonType === "Monthly") {
        feeBreakdown.monthlyFee = 4000; // Updated monthly fee
        feeAmount = feeBreakdown.registrationFee + feeBreakdown.monthlyFee;
      } else if (seasonType === "SixMonth") { // Updated from "Annual" to "SixMonth"
        feeBreakdown.annualFee = 18000; // Updated 6-month fee (no registration fee)
        feeAmount = feeBreakdown.annualFee; // No registration fee for 6-month plan
      }
    } else if (reservationType === "Temporary") {
      feeBreakdown.dailyFee = 200 * (daysBooked || 1); // Updated daily fee
      feeAmount = feeBreakdown.registrationFee + feeBreakdown.dailyFee;
    }

    // Mark seat as reserved (temporary status during payment)
    seat.status = "Reserved";
    seat.reservedBy = studentID; // Track who is trying to reserve
    await seat.save();

    // Create reservation (reservationID will be auto-generated by pre-save hook)
    const reservation = new Reservation({
      studentID,
      busID,
      seatNumber,
      reservationType,
      startDate: new Date(startDate),
      endDate: endDate ? new Date(endDate) : undefined,
      daysBooked: reservationType === "Temporary" ? daysBooked : undefined,
      feeAmount,
      feeBreakdown,
      paymentStatus: "Pending",
      status: "Pending",
      seasonType: reservationType === "Regular" ? seasonType : undefined
    });

    await reservation.save();

    res.status(201).json({
      message: "Reservation created - Please proceed to payment",
      reservation,
      requiresPayment: true
    });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
};

//READ (by student)
const getReservationsByStudent = async (req, res) => {
  try {
    const { studentID } = req.params;
    const reservations = await Reservation.find({ studentID }).sort({ createdAt: -1 });
    res.json(reservations);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
};

//UPDATE RESERVATION STATUS (Payment Simulation Result)
const updateReservationStatus = async (req, res) => {
  try {
    const { id } = req.params;
    const { status, paymentStatus } = req.body;

    // Validate status values
    if (!["Booked", "Cancelled"].includes(status)) {
      return res.status(400).json({ error: "Invalid status. Use 'Booked' or 'Cancelled'" });
    }

    const reservation = await Reservation.findById(id);
    if (!reservation) return res.status(404).json({ error: "Reservation not found" });

    // Update reservation status and payment status
    reservation.status = status;
    reservation.paymentStatus = paymentStatus || (status === "Booked" ? "Success" : "Failed");
    await reservation.save();

    // Update seat status based on payment result
    if (status === "Booked") {
      await Seat.findOneAndUpdate(
        { busID: reservation.busID, seatNumber: reservation.seatNumber }, 
        { 
          status: "Booked",
          reservedBy: reservation.studentID
        }
      );
      res.json({ 
        message: "Payment successful - Seat booked!", 
        reservation,
        paymentStatus: "success"
      });
    } else if (status === "Cancelled") {
      // Check if this was a renewal attempt
      const wasRenewal = await Reservation.findOne({
        busID: reservation.busID,
        seatNumber: reservation.seatNumber,
        studentID: reservation.studentID,
        status: "Completed",
        reservationType: "Regular"
      });
      
      // If it was a renewal, set back to Pending, otherwise set to Available
      const newStatus = wasRenewal ? "Pending" : "Available";
      await Seat.findOneAndUpdate(
        { busID: reservation.busID, seatNumber: reservation.seatNumber }, 
        { 
          status: newStatus,
          reservedBy: wasRenewal ? reservation.studentID : null
        }
      );
      res.json({ 
        message: "Payment failed - Reservation cancelled", 
        reservation,
        paymentStatus: "failed"
      });
    }

  } catch (err) {
    res.status(500).json({ error: err.message });
  }
};

//UPDATE (approve / cancel) - For admin use
const updateReservation = async (req, res) => {
  try {
    const { id } = req.params;
    const { status } = req.body;

    const reservation = await Reservation.findById(id);
    if (!reservation) return res.status(404).json({ error: "Reservation not found" });

    reservation.status = status;
    await reservation.save();

    if (status === "Booked") {
      await Seat.findOneAndUpdate(
        { busID: reservation.busID, seatNumber: reservation.seatNumber }, 
        { status: "Booked" }
      );
    }
    if (status === "Cancelled") {
      await Seat.findOneAndUpdate(
        { busID: reservation.busID, seatNumber: reservation.seatNumber }, 
        { status: "Available" }
      );
    }

    res.json({ message: "Reservation updated", reservation });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
};

//DELETE
const deleteReservation = async (req, res) => {
  try {
    const { id } = req.params;
    const reservation = await Reservation.findById(id);
    if (!reservation) return res.status(404).json({ error: "Reservation not found" });

    // Free seat back to available
    await Seat.findOneAndUpdate(
      { busID: reservation.busID, seatNumber: reservation.seatNumber }, 
      { status: "Available" }
    );

    await reservation.deleteOne();

    res.json({ message: "Reservation deleted" });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
};

module.exports = {
  createReservation,
  getReservationsByStudent,
  updateReservationStatus,
  updateReservation,
  deleteReservation,
};
