const mongoose = require("mongoose");

const reservationSchema = new mongoose.Schema({
  reservationID: {
    type: String,
    required: false, // Changed to false since it's auto-generated by pre-save hook
    unique: true,
    trim: true
  },
  studentID: {
    type: String, // Changed to String to store actual student ID like "SGS0001"
    required: true,
    trim: true
  },
  busID: {
    type: String, // Changed from ObjectId to String to handle "BUS001" format
    required: true
  },
  seatNumber: {
    type: Number,
    required: true,
    min: 1,
    max: 50
  },
  reservationType: {
    type: String,
    enum: ["Regular", "Temporary"],
    required: true
  },
  startDate: {
    type: Date,
    required: true
  },
  endDate: {
    type: Date,
    required: true // Required for both Regular and Temporary students
  },
  daysBooked: {
    type: Number,
    required: function() {
      return this.reservationType === "Temporary";
    },
    min: 1,
    validate: {
      validator: function(value) {
        // Only apply 14-day limit for temporary students
        if (this.reservationType === "Temporary") {
          return value <= 14;
        }
        // No limit for regular students
        return true;
      },
      message: "Temporary student bookings are limited to a maximum of 14 days (2 weeks)"
    }
  },
  feeAmount: {
    type: Number,
    required: true,
    min: 0
  },
  feeBreakdown: {
    registrationFee: {
      type: Number,
      default: 0
    },
    monthlyFee: {
      type: Number,
      default: 0
    },
    annualFee: {
      type: Number,
      default: 0
    },
    dailyFee: {
      type: Number,
      default: 0
    }
  },
  paymentStatus: {
    type: String,
    enum: ["Pending", "Success", "Failed"],
    default: "Pending"
  },
  status: {
    type: String,
    enum: ["Pending", "Booked", "Cancelled", "Completed"],
    default: "Pending"
  },
  seasonType: {
    type: String,
    enum: ["Monthly", "SixMonth"],
    required: function() {
      return this.reservationType === "Regular";
    }
  },
  createdAt: {
    type: Date,
    default: Date.now
  },
  updatedAt: {
    type: Date,
    default: Date.now
  }
});

// Generate unique reservation ID
reservationSchema.pre('save', function(next) {
  if (!this.reservationID) {
    this.reservationID = 'RES' + Date.now() + Math.floor(Math.random() * 1000);
  }
  this.updatedAt = Date.now();
  next();
});

module.exports = mongoose.model("Reservation", reservationSchema);
